{{- if .Values.clair.enabled }}
{{- range $configMapName, $configMap := .Values.clair.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMapName }}
data:
{{- range $dataKeyName, $dataValue := $configMap.data }}
  {{ $dataKeyName }}: {{ tpl (toYaml $dataValue) $ | indent 2}}
{{- end }}
---
{{- end }}
{{- end }}