{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "harbor.fullname" . }}-ingress"
  labels:
{{ include "harbor.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.hosts.core }}
    {{- if .Values.ingress.tls.secretName }}
    secretName: {{ .Values.ingress.tls.secretName }}
    {{- else }}
    secretName: "{{ template "harbor.fullname" . }}-ingress"
    {{- end }}
  - hosts:
    - {{ .Values.ingress.hosts.notary }}
    {{- if .Values.ingress.tls.notarySecretName }}
    secretName: {{ .Values.ingress.tls.notarySecretName }}
    {{- else }}
    secretName: "{{ template "harbor.fullname" . }}-ingress"
    {{- end }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.hosts.core }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "harbor.portal" . }}
          servicePort: 80
      - path: /api/
        backend:
          serviceName: {{ template "harbor.fullname" . }}-ui
          servicePort: 80
      - path: /service/
        backend:
          serviceName: {{ template "harbor.fullname" . }}-ui
          servicePort: 80
      - path: /v2/
        backend:
          serviceName: {{ template "harbor.fullname" . }}-ui
          servicePort: 80
      - path: /chartrepo/
        backend:
          serviceName: {{ template "harbor.fullname" . }}-ui
          servicePort: 80
      - path: /login
        backend:
          serviceName: {{ template "harbor.fullname" . }}-ui
          servicePort: 80
      - path: /log_out
        backend:
          serviceName: {{ template "harbor.fullname" . }}-ui
          servicePort: 80
      - path: /sendEmail
        backend:
          serviceName: {{ template "harbor.fullname" . }}-ui
          servicePort: 80
      - path: /language
        backend:
          serviceName: {{ template "harbor.fullname" . }}-ui
          servicePort: 80
      - path: /reset
        backend:
          serviceName: {{ template "harbor.fullname" . }}-ui
          servicePort: 80
      - path: /userExists
        backend:
          serviceName: {{ template "harbor.fullname" . }}-ui
          servicePort: 80
      - path: /reset_password
        backend:
          serviceName: {{ template "harbor.fullname" . }}-ui
          servicePort: 80
  {{- if .Values.notary.enabled }}
  - host: {{ .Values.ingress.hosts.notary }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "harbor.notaryServiceName" . }}
          servicePort: 4443
  {{- end }}
{{- end }}